### PR TITLE
Merged logos

### PR DESCRIPTION
**Pull request by amyrhoda**
Added sponsor logos to index page

### CODE REVIEW

**Comment by amyrhoda** [comment]
@gvwilson Can you check this and merge it? Or @katyhuff? Thanks!

**Comment by gvwilson** [comment]
OK, this is weird: I have merged your branch to my machine and done a 
local build, and while the sponsor logos are all in the right place, 
there's no change to 'index.html', so they don't show up there.  Commit 
85a4a88 added text and images to index.html, commit 2f26030 seemed to 
add text to index.html, and then - ah. 0a7f1a7 has a conflict in 
index.html, so it wasn't merged.  You'll have to pull from upstream's 
gh-pages, merge on your machine, then re-push.
Thanks,
Greg

**Comment by amyrhoda** [comment]
Dammit, I thought I fixed that already. Okay, I'll try again.

**Comment by amyrhoda** [comment]
I'm abandoning this PR and going back to the other one. I think I learned something.

**Pull request closed without merging**
